name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: ASP.NET,TeX,html,css,javascript,shell,lua,RenderScript,MDX,Vue,Perl,Dockerfile,Astro
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout_repositories: 15
          commits_authoring: timon vonk,timonv,timon,timonv@users.noreply.github.com
